// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iCBM.Infrastructure;

namespace iCBM.Infrastructure.Migrations
{
    [DbContext(typeof(CbmContext))]
    [Migration("20201220170500_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("iCBM.Domain.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Name = "ALL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "DZD"
                        },
                        new
                        {
                            Id = 32,
                            Name = "ARS"
                        },
                        new
                        {
                            Id = 36,
                            Name = "AUD"
                        },
                        new
                        {
                            Id = 44,
                            Name = "BSD"
                        },
                        new
                        {
                            Id = 48,
                            Name = "BHD"
                        },
                        new
                        {
                            Id = 50,
                            Name = "BDT"
                        },
                        new
                        {
                            Id = 51,
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 52,
                            Name = "BBD"
                        },
                        new
                        {
                            Id = 60,
                            Name = "BMD"
                        },
                        new
                        {
                            Id = 64,
                            Name = "BTN"
                        },
                        new
                        {
                            Id = 68,
                            Name = "BOB"
                        },
                        new
                        {
                            Id = 72,
                            Name = "BWP"
                        },
                        new
                        {
                            Id = 84,
                            Name = "BZD"
                        },
                        new
                        {
                            Id = 90,
                            Name = "SBD"
                        },
                        new
                        {
                            Id = 96,
                            Name = "BND"
                        },
                        new
                        {
                            Id = 104,
                            Name = "MMK"
                        },
                        new
                        {
                            Id = 108,
                            Name = "BIF"
                        },
                        new
                        {
                            Id = 116,
                            Name = "KHR"
                        },
                        new
                        {
                            Id = 124,
                            Name = "CAD"
                        },
                        new
                        {
                            Id = 132,
                            Name = "CVE"
                        },
                        new
                        {
                            Id = 136,
                            Name = "KYD"
                        },
                        new
                        {
                            Id = 144,
                            Name = "LKR"
                        },
                        new
                        {
                            Id = 152,
                            Name = "CLP"
                        },
                        new
                        {
                            Id = 156,
                            Name = "CNY"
                        },
                        new
                        {
                            Id = 170,
                            Name = "COP"
                        },
                        new
                        {
                            Id = 174,
                            Name = "KMF"
                        },
                        new
                        {
                            Id = 188,
                            Name = "CRC"
                        },
                        new
                        {
                            Id = 191,
                            Name = "HRK"
                        },
                        new
                        {
                            Id = 192,
                            Name = "CUP"
                        },
                        new
                        {
                            Id = 203,
                            Name = "CZK"
                        },
                        new
                        {
                            Id = 208,
                            Name = "DKK"
                        },
                        new
                        {
                            Id = 214,
                            Name = "DOP"
                        },
                        new
                        {
                            Id = 222,
                            Name = "SVC"
                        },
                        new
                        {
                            Id = 230,
                            Name = "ETB"
                        },
                        new
                        {
                            Id = 232,
                            Name = "ERN"
                        },
                        new
                        {
                            Id = 238,
                            Name = "FKP"
                        },
                        new
                        {
                            Id = 242,
                            Name = "FJD"
                        },
                        new
                        {
                            Id = 262,
                            Name = "DJF"
                        },
                        new
                        {
                            Id = 270,
                            Name = "GMD"
                        },
                        new
                        {
                            Id = 292,
                            Name = "GIP"
                        },
                        new
                        {
                            Id = 320,
                            Name = "GTQ"
                        },
                        new
                        {
                            Id = 324,
                            Name = "GNF"
                        },
                        new
                        {
                            Id = 328,
                            Name = "GYD"
                        },
                        new
                        {
                            Id = 332,
                            Name = "HTG"
                        },
                        new
                        {
                            Id = 340,
                            Name = "HNL"
                        },
                        new
                        {
                            Id = 344,
                            Name = "HKD"
                        },
                        new
                        {
                            Id = 348,
                            Name = "HUF"
                        },
                        new
                        {
                            Id = 352,
                            Name = "ISK"
                        },
                        new
                        {
                            Id = 356,
                            Name = "INR"
                        },
                        new
                        {
                            Id = 360,
                            Name = "IDR"
                        },
                        new
                        {
                            Id = 364,
                            Name = "IRR"
                        },
                        new
                        {
                            Id = 368,
                            Name = "IQD"
                        },
                        new
                        {
                            Id = 376,
                            Name = "ILS"
                        },
                        new
                        {
                            Id = 388,
                            Name = "JMD"
                        },
                        new
                        {
                            Id = 392,
                            Name = "JPY"
                        },
                        new
                        {
                            Id = 398,
                            Name = "KZT"
                        },
                        new
                        {
                            Id = 400,
                            Name = "JOD"
                        },
                        new
                        {
                            Id = 404,
                            Name = "KES"
                        },
                        new
                        {
                            Id = 408,
                            Name = "KPW"
                        },
                        new
                        {
                            Id = 410,
                            Name = "KRW"
                        },
                        new
                        {
                            Id = 414,
                            Name = "KWD"
                        },
                        new
                        {
                            Id = 417,
                            Name = "KGS"
                        },
                        new
                        {
                            Id = 418,
                            Name = "LAK"
                        },
                        new
                        {
                            Id = 422,
                            Name = "LBP"
                        },
                        new
                        {
                            Id = 426,
                            Name = "LSL"
                        },
                        new
                        {
                            Id = 430,
                            Name = "LRD"
                        },
                        new
                        {
                            Id = 434,
                            Name = "LYD"
                        },
                        new
                        {
                            Id = 446,
                            Name = "MOP"
                        },
                        new
                        {
                            Id = 454,
                            Name = "MWK"
                        },
                        new
                        {
                            Id = 458,
                            Name = "MYR"
                        },
                        new
                        {
                            Id = 462,
                            Name = "MVR"
                        },
                        new
                        {
                            Id = 480,
                            Name = "MUR"
                        },
                        new
                        {
                            Id = 484,
                            Name = "MXN"
                        },
                        new
                        {
                            Id = 496,
                            Name = "MNT"
                        },
                        new
                        {
                            Id = 498,
                            Name = "MDL"
                        },
                        new
                        {
                            Id = 504,
                            Name = "MAD"
                        },
                        new
                        {
                            Id = 512,
                            Name = "OMR"
                        },
                        new
                        {
                            Id = 516,
                            Name = "NAD"
                        },
                        new
                        {
                            Id = 524,
                            Name = "NPR"
                        },
                        new
                        {
                            Id = 532,
                            Name = "ANG"
                        },
                        new
                        {
                            Id = 533,
                            Name = "AWG"
                        },
                        new
                        {
                            Id = 548,
                            Name = "VUV"
                        },
                        new
                        {
                            Id = 554,
                            Name = "NZD"
                        },
                        new
                        {
                            Id = 558,
                            Name = "NIO"
                        },
                        new
                        {
                            Id = 566,
                            Name = "NGN"
                        },
                        new
                        {
                            Id = 578,
                            Name = "NOK"
                        },
                        new
                        {
                            Id = 586,
                            Name = "PKR"
                        },
                        new
                        {
                            Id = 590,
                            Name = "PAB"
                        },
                        new
                        {
                            Id = 598,
                            Name = "PGK"
                        },
                        new
                        {
                            Id = 600,
                            Name = "PYG"
                        },
                        new
                        {
                            Id = 604,
                            Name = "PEN"
                        },
                        new
                        {
                            Id = 608,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 634,
                            Name = "QAR"
                        },
                        new
                        {
                            Id = 643,
                            Name = "RUB"
                        },
                        new
                        {
                            Id = 646,
                            Name = "RWF"
                        },
                        new
                        {
                            Id = 654,
                            Name = "SHP"
                        },
                        new
                        {
                            Id = 682,
                            Name = "SAR"
                        },
                        new
                        {
                            Id = 690,
                            Name = "SCR"
                        },
                        new
                        {
                            Id = 694,
                            Name = "SLL"
                        },
                        new
                        {
                            Id = 702,
                            Name = "SGD"
                        },
                        new
                        {
                            Id = 704,
                            Name = "VND"
                        },
                        new
                        {
                            Id = 706,
                            Name = "SOS"
                        },
                        new
                        {
                            Id = 710,
                            Name = "ZAR"
                        },
                        new
                        {
                            Id = 728,
                            Name = "SSP"
                        },
                        new
                        {
                            Id = 748,
                            Name = "SZL"
                        },
                        new
                        {
                            Id = 752,
                            Name = "SEK"
                        },
                        new
                        {
                            Id = 756,
                            Name = "CHF"
                        },
                        new
                        {
                            Id = 760,
                            Name = "SYP"
                        },
                        new
                        {
                            Id = 764,
                            Name = "THB"
                        },
                        new
                        {
                            Id = 776,
                            Name = "TOP"
                        },
                        new
                        {
                            Id = 780,
                            Name = "TTD"
                        },
                        new
                        {
                            Id = 784,
                            Name = "AED"
                        },
                        new
                        {
                            Id = 788,
                            Name = "TND"
                        },
                        new
                        {
                            Id = 800,
                            Name = "UGX"
                        },
                        new
                        {
                            Id = 807,
                            Name = "MKD"
                        },
                        new
                        {
                            Id = 818,
                            Name = "EGP"
                        },
                        new
                        {
                            Id = 826,
                            Name = "GBP"
                        },
                        new
                        {
                            Id = 834,
                            Name = "TZS"
                        },
                        new
                        {
                            Id = 840,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 858,
                            Name = "UYU"
                        },
                        new
                        {
                            Id = 860,
                            Name = "UZS"
                        },
                        new
                        {
                            Id = 882,
                            Name = "WST"
                        },
                        new
                        {
                            Id = 886,
                            Name = "YER"
                        },
                        new
                        {
                            Id = 901,
                            Name = "TWD"
                        },
                        new
                        {
                            Id = 927,
                            Name = "UYW"
                        },
                        new
                        {
                            Id = 928,
                            Name = "VES"
                        },
                        new
                        {
                            Id = 929,
                            Name = "MRU"
                        },
                        new
                        {
                            Id = 930,
                            Name = "STN"
                        },
                        new
                        {
                            Id = 931,
                            Name = "CUC"
                        },
                        new
                        {
                            Id = 932,
                            Name = "ZWL"
                        },
                        new
                        {
                            Id = 933,
                            Name = "BYN"
                        },
                        new
                        {
                            Id = 934,
                            Name = "TMT"
                        },
                        new
                        {
                            Id = 936,
                            Name = "GHS"
                        },
                        new
                        {
                            Id = 938,
                            Name = "SDG"
                        },
                        new
                        {
                            Id = 940,
                            Name = "UYI"
                        },
                        new
                        {
                            Id = 941,
                            Name = "RSD"
                        },
                        new
                        {
                            Id = 943,
                            Name = "MZN"
                        },
                        new
                        {
                            Id = 944,
                            Name = "AZN"
                        },
                        new
                        {
                            Id = 946,
                            Name = "RON"
                        },
                        new
                        {
                            Id = 947,
                            Name = "CHE"
                        },
                        new
                        {
                            Id = 948,
                            Name = "CHW"
                        },
                        new
                        {
                            Id = 949,
                            Name = "TRY"
                        },
                        new
                        {
                            Id = 950,
                            Name = "XAF"
                        },
                        new
                        {
                            Id = 951,
                            Name = "XCD"
                        },
                        new
                        {
                            Id = 952,
                            Name = "XOF"
                        },
                        new
                        {
                            Id = 953,
                            Name = "XPF"
                        },
                        new
                        {
                            Id = 955,
                            Name = "XBA"
                        },
                        new
                        {
                            Id = 956,
                            Name = "XBB"
                        },
                        new
                        {
                            Id = 957,
                            Name = "XBC"
                        },
                        new
                        {
                            Id = 958,
                            Name = "XBD"
                        },
                        new
                        {
                            Id = 959,
                            Name = "XAU"
                        },
                        new
                        {
                            Id = 960,
                            Name = "XDR"
                        },
                        new
                        {
                            Id = 961,
                            Name = "XAG"
                        },
                        new
                        {
                            Id = 962,
                            Name = "XPT"
                        },
                        new
                        {
                            Id = 963,
                            Name = "XTS"
                        },
                        new
                        {
                            Id = 964,
                            Name = "XPD"
                        },
                        new
                        {
                            Id = 965,
                            Name = "XUA"
                        },
                        new
                        {
                            Id = 967,
                            Name = "ZMW"
                        },
                        new
                        {
                            Id = 968,
                            Name = "SRD"
                        },
                        new
                        {
                            Id = 969,
                            Name = "MGA"
                        },
                        new
                        {
                            Id = 970,
                            Name = "COU"
                        },
                        new
                        {
                            Id = 971,
                            Name = "AFN"
                        },
                        new
                        {
                            Id = 972,
                            Name = "TJS"
                        },
                        new
                        {
                            Id = 973,
                            Name = "AOA"
                        },
                        new
                        {
                            Id = 975,
                            Name = "BGN"
                        },
                        new
                        {
                            Id = 976,
                            Name = "CDF"
                        },
                        new
                        {
                            Id = 977,
                            Name = "BAM"
                        },
                        new
                        {
                            Id = 978,
                            Name = "EUR"
                        },
                        new
                        {
                            Id = 979,
                            Name = "MXV"
                        },
                        new
                        {
                            Id = 980,
                            Name = "UAH"
                        },
                        new
                        {
                            Id = 981,
                            Name = "GEL"
                        },
                        new
                        {
                            Id = 984,
                            Name = "BOV"
                        },
                        new
                        {
                            Id = 985,
                            Name = "PLN"
                        },
                        new
                        {
                            Id = 986,
                            Name = "BRL"
                        },
                        new
                        {
                            Id = 990,
                            Name = "CLF"
                        },
                        new
                        {
                            Id = 994,
                            Name = "XSU"
                        },
                        new
                        {
                            Id = 997,
                            Name = "USN"
                        },
                        new
                        {
                            Id = 999,
                            Name = "XXX"
                        });
                });

            modelBuilder.Entity("iCBM.Domain.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpirationDate");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpirationDate");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Expense", b =>
                {
                    b.HasOne("iCBM.Domain.Models.Supplier", "Supplier")
                        .WithMany("Expenses")
                        .HasForeignKey("SupplierId");

                    b.OwnsOne("iCBM.Domain.Models.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(38, 2)
                                .HasColumnType("decimal(38,2)")
                                .HasColumnName("Amount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("CurrencyId");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Supplier", b =>
                {
                    b.OwnsOne("iCBM.Domain.Models.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(248)
                                .HasColumnType("nvarchar(248)")
                                .HasColumnName("AddressLine1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(248)
                                .HasColumnType("nvarchar(248)")
                                .HasColumnName("AddressLine2");

                            b1.Property<string>("City")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("City");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(248)
                                .HasColumnType("nvarchar(248)")
                                .HasColumnName("EmailAddress");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<string>("Zipcode")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("Zipcode");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Supplier");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("ContactDetails");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Supplier", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
