// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iCBM.Infrastructure;

namespace iCBM.Infrastructure.Migrations
{
    [DbContext(typeof(CbmContext))]
    [Migration("20210103130002_ChangeIcon")]
    partial class ChangeIcon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("iCBM.Domain.Enums.Color", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "pink"
                        },
                        new
                        {
                            Id = 3,
                            Name = "purple"
                        },
                        new
                        {
                            Id = 4,
                            Name = "deep-purple"
                        },
                        new
                        {
                            Id = 5,
                            Name = "indigo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "blue"
                        },
                        new
                        {
                            Id = 7,
                            Name = "light-blue"
                        },
                        new
                        {
                            Id = 8,
                            Name = "cyan"
                        },
                        new
                        {
                            Id = 9,
                            Name = "teal"
                        },
                        new
                        {
                            Id = 10,
                            Name = "green"
                        },
                        new
                        {
                            Id = 11,
                            Name = "light-green"
                        },
                        new
                        {
                            Id = 12,
                            Name = "lime"
                        },
                        new
                        {
                            Id = 13,
                            Name = "yellow"
                        },
                        new
                        {
                            Id = 14,
                            Name = "amber"
                        },
                        new
                        {
                            Id = 15,
                            Name = "orange"
                        },
                        new
                        {
                            Id = 16,
                            Name = "deep-orange"
                        },
                        new
                        {
                            Id = 17,
                            Name = "brown"
                        },
                        new
                        {
                            Id = 18,
                            Name = "blue-grey"
                        },
                        new
                        {
                            Id = 19,
                            Name = "grey"
                        });
                });

            modelBuilder.Entity("iCBM.Domain.Enums.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Name = "ALL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "DZD"
                        },
                        new
                        {
                            Id = 32,
                            Name = "ARS"
                        },
                        new
                        {
                            Id = 36,
                            Name = "AUD"
                        },
                        new
                        {
                            Id = 44,
                            Name = "BSD"
                        },
                        new
                        {
                            Id = 48,
                            Name = "BHD"
                        },
                        new
                        {
                            Id = 50,
                            Name = "BDT"
                        },
                        new
                        {
                            Id = 51,
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 52,
                            Name = "BBD"
                        },
                        new
                        {
                            Id = 60,
                            Name = "BMD"
                        },
                        new
                        {
                            Id = 64,
                            Name = "BTN"
                        },
                        new
                        {
                            Id = 68,
                            Name = "BOB"
                        },
                        new
                        {
                            Id = 72,
                            Name = "BWP"
                        },
                        new
                        {
                            Id = 84,
                            Name = "BZD"
                        },
                        new
                        {
                            Id = 90,
                            Name = "SBD"
                        },
                        new
                        {
                            Id = 96,
                            Name = "BND"
                        },
                        new
                        {
                            Id = 104,
                            Name = "MMK"
                        },
                        new
                        {
                            Id = 108,
                            Name = "BIF"
                        },
                        new
                        {
                            Id = 116,
                            Name = "KHR"
                        },
                        new
                        {
                            Id = 124,
                            Name = "CAD"
                        },
                        new
                        {
                            Id = 132,
                            Name = "CVE"
                        },
                        new
                        {
                            Id = 136,
                            Name = "KYD"
                        },
                        new
                        {
                            Id = 144,
                            Name = "LKR"
                        },
                        new
                        {
                            Id = 152,
                            Name = "CLP"
                        },
                        new
                        {
                            Id = 156,
                            Name = "CNY"
                        },
                        new
                        {
                            Id = 170,
                            Name = "COP"
                        },
                        new
                        {
                            Id = 174,
                            Name = "KMF"
                        },
                        new
                        {
                            Id = 188,
                            Name = "CRC"
                        },
                        new
                        {
                            Id = 191,
                            Name = "HRK"
                        },
                        new
                        {
                            Id = 192,
                            Name = "CUP"
                        },
                        new
                        {
                            Id = 203,
                            Name = "CZK"
                        },
                        new
                        {
                            Id = 208,
                            Name = "DKK"
                        },
                        new
                        {
                            Id = 214,
                            Name = "DOP"
                        },
                        new
                        {
                            Id = 222,
                            Name = "SVC"
                        },
                        new
                        {
                            Id = 230,
                            Name = "ETB"
                        },
                        new
                        {
                            Id = 232,
                            Name = "ERN"
                        },
                        new
                        {
                            Id = 238,
                            Name = "FKP"
                        },
                        new
                        {
                            Id = 242,
                            Name = "FJD"
                        },
                        new
                        {
                            Id = 262,
                            Name = "DJF"
                        },
                        new
                        {
                            Id = 270,
                            Name = "GMD"
                        },
                        new
                        {
                            Id = 292,
                            Name = "GIP"
                        },
                        new
                        {
                            Id = 320,
                            Name = "GTQ"
                        },
                        new
                        {
                            Id = 324,
                            Name = "GNF"
                        },
                        new
                        {
                            Id = 328,
                            Name = "GYD"
                        },
                        new
                        {
                            Id = 332,
                            Name = "HTG"
                        },
                        new
                        {
                            Id = 340,
                            Name = "HNL"
                        },
                        new
                        {
                            Id = 344,
                            Name = "HKD"
                        },
                        new
                        {
                            Id = 348,
                            Name = "HUF"
                        },
                        new
                        {
                            Id = 352,
                            Name = "ISK"
                        },
                        new
                        {
                            Id = 356,
                            Name = "INR"
                        },
                        new
                        {
                            Id = 360,
                            Name = "IDR"
                        },
                        new
                        {
                            Id = 364,
                            Name = "IRR"
                        },
                        new
                        {
                            Id = 368,
                            Name = "IQD"
                        },
                        new
                        {
                            Id = 376,
                            Name = "ILS"
                        },
                        new
                        {
                            Id = 388,
                            Name = "JMD"
                        },
                        new
                        {
                            Id = 392,
                            Name = "JPY"
                        },
                        new
                        {
                            Id = 398,
                            Name = "KZT"
                        },
                        new
                        {
                            Id = 400,
                            Name = "JOD"
                        },
                        new
                        {
                            Id = 404,
                            Name = "KES"
                        },
                        new
                        {
                            Id = 408,
                            Name = "KPW"
                        },
                        new
                        {
                            Id = 410,
                            Name = "KRW"
                        },
                        new
                        {
                            Id = 414,
                            Name = "KWD"
                        },
                        new
                        {
                            Id = 417,
                            Name = "KGS"
                        },
                        new
                        {
                            Id = 418,
                            Name = "LAK"
                        },
                        new
                        {
                            Id = 422,
                            Name = "LBP"
                        },
                        new
                        {
                            Id = 426,
                            Name = "LSL"
                        },
                        new
                        {
                            Id = 430,
                            Name = "LRD"
                        },
                        new
                        {
                            Id = 434,
                            Name = "LYD"
                        },
                        new
                        {
                            Id = 446,
                            Name = "MOP"
                        },
                        new
                        {
                            Id = 454,
                            Name = "MWK"
                        },
                        new
                        {
                            Id = 458,
                            Name = "MYR"
                        },
                        new
                        {
                            Id = 462,
                            Name = "MVR"
                        },
                        new
                        {
                            Id = 480,
                            Name = "MUR"
                        },
                        new
                        {
                            Id = 484,
                            Name = "MXN"
                        },
                        new
                        {
                            Id = 496,
                            Name = "MNT"
                        },
                        new
                        {
                            Id = 498,
                            Name = "MDL"
                        },
                        new
                        {
                            Id = 504,
                            Name = "MAD"
                        },
                        new
                        {
                            Id = 512,
                            Name = "OMR"
                        },
                        new
                        {
                            Id = 516,
                            Name = "NAD"
                        },
                        new
                        {
                            Id = 524,
                            Name = "NPR"
                        },
                        new
                        {
                            Id = 532,
                            Name = "ANG"
                        },
                        new
                        {
                            Id = 533,
                            Name = "AWG"
                        },
                        new
                        {
                            Id = 548,
                            Name = "VUV"
                        },
                        new
                        {
                            Id = 554,
                            Name = "NZD"
                        },
                        new
                        {
                            Id = 558,
                            Name = "NIO"
                        },
                        new
                        {
                            Id = 566,
                            Name = "NGN"
                        },
                        new
                        {
                            Id = 578,
                            Name = "NOK"
                        },
                        new
                        {
                            Id = 586,
                            Name = "PKR"
                        },
                        new
                        {
                            Id = 590,
                            Name = "PAB"
                        },
                        new
                        {
                            Id = 598,
                            Name = "PGK"
                        },
                        new
                        {
                            Id = 600,
                            Name = "PYG"
                        },
                        new
                        {
                            Id = 604,
                            Name = "PEN"
                        },
                        new
                        {
                            Id = 608,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 634,
                            Name = "QAR"
                        },
                        new
                        {
                            Id = 643,
                            Name = "RUB"
                        },
                        new
                        {
                            Id = 646,
                            Name = "RWF"
                        },
                        new
                        {
                            Id = 654,
                            Name = "SHP"
                        },
                        new
                        {
                            Id = 682,
                            Name = "SAR"
                        },
                        new
                        {
                            Id = 690,
                            Name = "SCR"
                        },
                        new
                        {
                            Id = 694,
                            Name = "SLL"
                        },
                        new
                        {
                            Id = 702,
                            Name = "SGD"
                        },
                        new
                        {
                            Id = 704,
                            Name = "VND"
                        },
                        new
                        {
                            Id = 706,
                            Name = "SOS"
                        },
                        new
                        {
                            Id = 710,
                            Name = "ZAR"
                        },
                        new
                        {
                            Id = 728,
                            Name = "SSP"
                        },
                        new
                        {
                            Id = 748,
                            Name = "SZL"
                        },
                        new
                        {
                            Id = 752,
                            Name = "SEK"
                        },
                        new
                        {
                            Id = 756,
                            Name = "CHF"
                        },
                        new
                        {
                            Id = 760,
                            Name = "SYP"
                        },
                        new
                        {
                            Id = 764,
                            Name = "THB"
                        },
                        new
                        {
                            Id = 776,
                            Name = "TOP"
                        },
                        new
                        {
                            Id = 780,
                            Name = "TTD"
                        },
                        new
                        {
                            Id = 784,
                            Name = "AED"
                        },
                        new
                        {
                            Id = 788,
                            Name = "TND"
                        },
                        new
                        {
                            Id = 800,
                            Name = "UGX"
                        },
                        new
                        {
                            Id = 807,
                            Name = "MKD"
                        },
                        new
                        {
                            Id = 818,
                            Name = "EGP"
                        },
                        new
                        {
                            Id = 826,
                            Name = "GBP"
                        },
                        new
                        {
                            Id = 834,
                            Name = "TZS"
                        },
                        new
                        {
                            Id = 840,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 858,
                            Name = "UYU"
                        },
                        new
                        {
                            Id = 860,
                            Name = "UZS"
                        },
                        new
                        {
                            Id = 882,
                            Name = "WST"
                        },
                        new
                        {
                            Id = 886,
                            Name = "YER"
                        },
                        new
                        {
                            Id = 901,
                            Name = "TWD"
                        },
                        new
                        {
                            Id = 927,
                            Name = "UYW"
                        },
                        new
                        {
                            Id = 928,
                            Name = "VES"
                        },
                        new
                        {
                            Id = 929,
                            Name = "MRU"
                        },
                        new
                        {
                            Id = 930,
                            Name = "STN"
                        },
                        new
                        {
                            Id = 931,
                            Name = "CUC"
                        },
                        new
                        {
                            Id = 932,
                            Name = "ZWL"
                        },
                        new
                        {
                            Id = 933,
                            Name = "BYN"
                        },
                        new
                        {
                            Id = 934,
                            Name = "TMT"
                        },
                        new
                        {
                            Id = 936,
                            Name = "GHS"
                        },
                        new
                        {
                            Id = 938,
                            Name = "SDG"
                        },
                        new
                        {
                            Id = 940,
                            Name = "UYI"
                        },
                        new
                        {
                            Id = 941,
                            Name = "RSD"
                        },
                        new
                        {
                            Id = 943,
                            Name = "MZN"
                        },
                        new
                        {
                            Id = 944,
                            Name = "AZN"
                        },
                        new
                        {
                            Id = 946,
                            Name = "RON"
                        },
                        new
                        {
                            Id = 947,
                            Name = "CHE"
                        },
                        new
                        {
                            Id = 948,
                            Name = "CHW"
                        },
                        new
                        {
                            Id = 949,
                            Name = "TRY"
                        },
                        new
                        {
                            Id = 950,
                            Name = "XAF"
                        },
                        new
                        {
                            Id = 951,
                            Name = "XCD"
                        },
                        new
                        {
                            Id = 952,
                            Name = "XOF"
                        },
                        new
                        {
                            Id = 953,
                            Name = "XPF"
                        },
                        new
                        {
                            Id = 955,
                            Name = "XBA"
                        },
                        new
                        {
                            Id = 956,
                            Name = "XBB"
                        },
                        new
                        {
                            Id = 957,
                            Name = "XBC"
                        },
                        new
                        {
                            Id = 958,
                            Name = "XBD"
                        },
                        new
                        {
                            Id = 959,
                            Name = "XAU"
                        },
                        new
                        {
                            Id = 960,
                            Name = "XDR"
                        },
                        new
                        {
                            Id = 961,
                            Name = "XAG"
                        },
                        new
                        {
                            Id = 962,
                            Name = "XPT"
                        },
                        new
                        {
                            Id = 963,
                            Name = "XTS"
                        },
                        new
                        {
                            Id = 964,
                            Name = "XPD"
                        },
                        new
                        {
                            Id = 965,
                            Name = "XUA"
                        },
                        new
                        {
                            Id = 967,
                            Name = "ZMW"
                        },
                        new
                        {
                            Id = 968,
                            Name = "SRD"
                        },
                        new
                        {
                            Id = 969,
                            Name = "MGA"
                        },
                        new
                        {
                            Id = 970,
                            Name = "COU"
                        },
                        new
                        {
                            Id = 971,
                            Name = "AFN"
                        },
                        new
                        {
                            Id = 972,
                            Name = "TJS"
                        },
                        new
                        {
                            Id = 973,
                            Name = "AOA"
                        },
                        new
                        {
                            Id = 975,
                            Name = "BGN"
                        },
                        new
                        {
                            Id = 976,
                            Name = "CDF"
                        },
                        new
                        {
                            Id = 977,
                            Name = "BAM"
                        },
                        new
                        {
                            Id = 978,
                            Name = "EUR"
                        },
                        new
                        {
                            Id = 979,
                            Name = "MXV"
                        },
                        new
                        {
                            Id = 980,
                            Name = "UAH"
                        },
                        new
                        {
                            Id = 981,
                            Name = "GEL"
                        },
                        new
                        {
                            Id = 984,
                            Name = "BOV"
                        },
                        new
                        {
                            Id = 985,
                            Name = "PLN"
                        },
                        new
                        {
                            Id = 986,
                            Name = "BRL"
                        },
                        new
                        {
                            Id = 990,
                            Name = "CLF"
                        },
                        new
                        {
                            Id = 994,
                            Name = "XSU"
                        },
                        new
                        {
                            Id = 997,
                            Name = "USN"
                        },
                        new
                        {
                            Id = 999,
                            Name = "XXX"
                        });
                });

            modelBuilder.Entity("iCBM.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe9fac56-7230-4c16-81c0-be9b61fdc861"),
                            ColorId = 6,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "store",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Materials",
                            OwnerId = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6")
                        },
                        new
                        {
                            Id = new Guid("fd547340-199e-49be-88ed-3d7570ddaf4b"),
                            ColorId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "store",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Services",
                            OwnerId = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6")
                        },
                        new
                        {
                            Id = new Guid("1c7fdef1-1db4-45be-9058-eeb22d80ed01"),
                            ColorId = 13,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "store",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Other",
                            OwnerId = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6")
                        });
                });

            modelBuilder.Entity("iCBM.Domain.Models.ConstructionStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlannedFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ConstructionStages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a4d56e5-c062-4484-92d9-4a2347eaf809"),
                            ColorId = 6,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "house",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SSO",
                            OwnerId = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6"),
                            PlannedFinishDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedStartDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0a7bc129-c7d5-401c-864c-6f23aabd5f10"),
                            ColorId = 6,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "house",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SSZ",
                            OwnerId = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6"),
                            PlannedFinishDate = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedStartDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("68880b0e-cd7d-44b3-ba87-11c8904af433"),
                            ColorId = 6,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "house",
                            IsDeleted = false,
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Finishing",
                            OwnerId = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6"),
                            PlannedFinishDate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedStartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("iCBM.Domain.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConstructionStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ConstructionStageId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<DateTime>("PublishDated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("iCBM.Domain.Models.NotificationReads", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReadOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationReads");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("iCBM.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af76108b-11ee-448b-907f-0dcaccc8adf6"),
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@example.com",
                            FirstName = "Harry",
                            IsDeleted = false,
                            LastName = "Potter",
                            ModifiedBy = "System",
                            ModifiedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "AQAAAAEAACcQAAAAEAgypWPs8S/vBidt0j/vANTzN25W/BkUbO/MhGadoWBpCcEhFvnJ5VUV+lPLHBQq/Q=="
                        });
                });

            modelBuilder.Entity("iCBM.Domain.Models.Category", b =>
                {
                    b.HasOne("iCBM.Domain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iCBM.Domain.Models.ConstructionStage", b =>
                {
                    b.HasOne("iCBM.Domain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Expense", b =>
                {
                    b.HasOne("iCBM.Domain.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iCBM.Domain.Models.ConstructionStage", "ConstructionStage")
                        .WithMany("Expenses")
                        .HasForeignKey("ConstructionStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iCBM.Domain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iCBM.Domain.Models.Supplier", "Supplier")
                        .WithMany("Expenses")
                        .HasForeignKey("SupplierId");

                    b.OwnsOne("iCBM.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(38, 2)
                                .HasColumnType("decimal(38,2)")
                                .HasColumnName("Amount");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("CurrencyId");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount");

                    b.Navigation("Category");

                    b.Navigation("ConstructionStage");

                    b.Navigation("Owner");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("iCBM.Domain.Models.NotificationReads", b =>
                {
                    b.HasOne("iCBM.Domain.Models.Notification", "Notification")
                        .WithMany("Reads")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iCBM.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Supplier", b =>
                {
                    b.HasOne("iCBM.Domain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("iCBM.Domain.ValueObjects.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AddressLine1")
                                .HasMaxLength(248)
                                .HasColumnType("nvarchar(248)")
                                .HasColumnName("AddressLine1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(248)
                                .HasColumnType("nvarchar(248)")
                                .HasColumnName("AddressLine2");

                            b1.Property<string>("City")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("City");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(248)
                                .HasColumnType("nvarchar(248)")
                                .HasColumnName("EmailAddress");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<string>("Zipcode")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("Zipcode");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("ContactDetails");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("iCBM.Domain.Models.ConstructionStage", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Notification", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("iCBM.Domain.Models.Supplier", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
