@url = https://localhost:5001/expenses

###
GET {{url}}
Content-Type:  application/json

###
POST {{url}}
Content-Type:  application/json

{
  "name": "My first expense",
  "description": "This is my very first expense",
  "amount": 100.23,
  "currency": "PLN",
  "expenseTime": "2020-12-20T13:47:04.143Z",
  "categoryName": "Other",
  "categoryId": null,
  "supplierId": "3c0d29b8-535e-48d4-8f82-7565b2443c8c"
}