@url = https://localhost:5001/expenses
@accessToken = secret
@expenseId = 00000000-0000-0000-0000-000000000000

###
GET {{url}}
Content-Type:  application/json
Authorization: Bearer {{accessToken}}

###
GET {{url}}/{{expenseId}}
Content-Type:  application/json
Authorization: Bearer {{accessToken}}

###
POST {{url}}
Content-Type:  application/json
Authorization: Bearer {{accessToken}}

{
  "name": "My first expense",
  "description": "This is my very first expense",
  "amount": 100.23,
  "currency": "PLN",
  "expenseTime": "2020-12-20T13:47:04.143Z",
  "categoryName": "Other",
  "categoryId": null,
  "supplierId": null
}